create_clock -period 16.000 -name clk -waveform {0.000 8.000} [get_ports clk]

set_false_path -from [get_ports {reset_external}]
set_false_path -to [get_ports {halt}]
set_false_path -to [get_ports {ucode_out[*]}]
set_false_path -to [get_ports {ucode_addr_out[*]}]
set_false_path -to [get_ports {ir1_out[*]}]
set_false_path -to [get_ports {bc_out[*]}]
set_false_path -to [get_ports {arg_lo_out[*]}]
set_false_path -to [get_ports {arg_hi_out[*]}]
